In [1]:
import pandas as pd

# Cargar el dataset
df = pd.read_csv('iar_Reservaciones.csv')

C:\Users\Karla Palma\AppData\Local\Temp\ipykernel_23408\1675693029.py:4: DtypeWarning: Columns (22,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('iar_Reservaciones.csv')

In [2]:
df.shape

(203002, 49)

In [3]:
# Verificar valores nulos 
missing_counts = df.isnull().sum()
print(missing_counts[missing_counts > 0])

h_correo_e    203002
h_nom         203002
dtype: int64

In [4]:
# Eliminar columnas con valores nulos
df = df.drop(columns=['h_correo_e', 'h_nom'])

In [5]:
print(df.isnull().sum().sum())  # total de valores faltantes

0

In [6]:
# Convertir valores con especios en blanco a NaN
df = df.replace(r'^\s*$', pd.NA, regex=True)

In [7]:
# Nuevos valores nulos
missing_counts = df.isnull().sum()
print(missing_counts[missing_counts > 0])

h_fec_lld             2
h_fec_reg          1550
h_fec_sda            34
h_can_res           492
h_cod_reserva    128142
h_edo                 2
h_codigop         57324
h_ult_cam_fec       533
dtype: int64

In [8]:
# Eliminar columnas con gran numero de valores nulos
df = df.drop(columns=['h_cod_reserva', 'h_codigop'])

In [9]:
# Eliminar filas con valores nulos
df = df.dropna()

In [16]:
# Verificar y eliminar filas duplicadas
duplicados = df.duplicated()
print(f"\nNúmero de filas duplicadas: {duplicados.sum()}")
df = df.drop_duplicates()

Número de filas duplicadas: 0

In [10]:
# Nuevas dimensiones del dataset
df.shape

(201412, 45)

In [11]:
for column_name in df.columns:
    value_counts = df[column_name].value_counts()
    print("Column Name: ", column_name)
    print(value_counts)

Column Name:  ID_Reserva
0         1
135255    1
135257    1
135258    1
135259    1
         ..
67565     1
67566     1
67567     1
67568     1
203001    1
Name: ID_Reserva, Length: 201412, dtype: int64
Column Name:  Fecha_hoy
2020-02-18    1496
2020-04-02    1484
2019-04-02    1465
2020-02-20    1372
2020-03-04    1162
              ...
2021-01-19       6
2019-01-06       6
2019-01-27       4
2019-01-20       1
2019-02-03       1
Name: Fecha_hoy, Length: 824, dtype: int64
Column Name:  h_res_fec
20190402    2930
20190502    2316
20190625    2204
20190315    1788
20190731    1608
            ...
20200418      10
20190127       8
20190120       2
20190203       2
20200405       2
Name: h_res_fec, Length: 481, dtype: int64
Column Name:  h_res_fec_ok
2019-04-02     2930
2019-05-02     2316
2019-06-25     2204
2019-03-15     1788
2019-07-31     1608
               ...
2020-04-18       10
2019-01-27        8
2019-01-20        2
2019-02-03        2
2020-04-05        2
Name: h_res_fec_ok, Length: 481, dtype: int64
Column Name:  h_res_fec_okt
2019-04-02    2930
2019-05-02    2316
2019-06-25    2204
2019-03-15    1788
2019-07-31    1608
              ...
2020-04-18      10
2019-01-27       8
2019-01-20       2
2019-02-03       2
2020-04-05       2
Name: h_res_fec_okt, Length: 481, dtype: int64
Column Name:  h_num_per
0     100019
2      71325
3      14922
4       7710
1       4900
5       1280
6        781
8        228
7         96
12        40
10        21
11        18
9         17
17        13
32        10
16         8
18         6
14         6
19         5
13         3
20         2
15         2
Name: h_num_per, dtype: int64
Column Name:  aa_h_num_per
0     101393
2      70108
3      14861
4       7654
1       4887
5       1276
6        775
8        215
7         96
12        38
10        20
11        18
9         17
17        13
32        10
16         8
18         6
14         6
19         5
13         3
20         2
15         1
Name: aa_h_num_per, dtype: int64
Column Name:  h_num_adu
0     100019
2      79629
3      11933
1       5607
4       2956
5        536
6        423
8        156
7         43
15        24
10        23
12        22
9         20
11         9
14         8
13         4
Name: h_num_adu, dtype: int64
Column Name:  aa_h_num_adu
0     101393
2      78389
3      11866
1       5593
4       2927
5        534
6        418
8        143
7         43
10        23
15        23
12        20
9         19
11         9
14         8
13         4
Name: aa_h_num_adu, dtype: int64
Column Name:  h_num_men
0     196972
1       2645
2       1555
3        168
4         31
5         17
15        10
7          7
6          6
8          1
Name: h_num_men, dtype: int64
Column Name:  aa_h_num_men
0     197024
1       2613
2       1538
3        165
4         31
5         17
15        10
7          7
6          6
8          1
Name: aa_h_num_men, dtype: int64
Column Name:  h_num_noc
0      100222
3       38432
2       28486
4       16274
7        8672
1        4675
5        2477
6        1008
14        643
8         140
10         94
9          66
11         65
15         36
12         29
13         17
21         15
28         10
16          7
35          6
20          5
17          4
19          3
182         3
36          2
18          2
89          2
63          2
87          2
22          1
48          1
81          1
84          1
687         1
52          1
24          1
27          1
191         1
321         1
74          1
59          1
34          1
Name: h_num_noc, dtype: int64
Column Name:  aa_h_num_noc
0      101596
3       37757
2       28128
4       16048
7        8612
1        4669
5        2463
6        1007
14        643
8         138
10         94
9          66
11         64
12         29
13         17
21         15
28         10
16          7
15          7
35          6
20          5
17          4
182         3
19          3
36          2
63          2
87          2
18          2
321         1
74          1
27          1
24          1
52          1
191         1
84          1
34          1
48          1
22          1
81          1
687         1
59          1
Name: aa_h_num_noc, dtype: int64
Column Name:  h_tot_hab
1    100907
0    100019
2       308
3       166
4         8
5         3
6         1
Name: h_tot_hab, dtype: int64
Column Name:  aa_h_tot_hab
0    101393
1     99551
2       296
3       160
4         8
5         3
6         1
Name: aa_h_tot_hab, dtype: int64
Column Name:  ID_Programa
1    201412
Name: ID_Programa, dtype: int64
Column Name:  ID_Paquete
1    116562
2     84716
5        92
3        40
4         2
Name: ID_Paquete, dtype: int64
Column Name:  ID_Segmento_Comp
17    73066
14    27298
5     26630
16    16776
12    15425
18     9082
1      6013
13     5770
8      4579
10     3212
19     3185
11     2811
9      2716
7      2020
6      1532
4       677
0       578
2        34
15        4
3         4
Name: ID_Segmento_Comp, dtype: int64
Column Name:  ID_Agencia
99     31521
112    25697
86     12973
14     12189
116     8846
       ...
37        10
57         8
118        6
115        4
64         2
Name: ID_Agencia, Length: 120, dtype: int64
Column Name:  ID_empresa
1    201412
Name: ID_empresa, dtype: int64
Column Name:  ID_Tipo_Habitacion
4     51996
19    50840
17    30806
6     13824
25    11100
13    10445
5      6029
23     5785
26     4907
24     3843
7      2124
27     1976
21     1787
12     1356
18     1328
22     1156
20      354
14      338
1       229
2       203
3       190
11      170
15      150
10      146
9       136
8       118
16       66
0        10
Name: ID_Tipo_Habitacion, dtype: int64
Column Name:  ID_canal
1     82061
4     80875
10    19743
7      6163
0      5848
8      2225
13     1738
9      1092
5       896
11      347
3       160
2       140
6       120
12        4
Name: ID_canal, dtype: int64
Column Name:  h_fec_lld
20190506    1368
20190515    1199
20190213    1191
20191107    1153
20201119    1102
            ...
20190226       1
20190228       1
20190426       1
20191105       1
20210327       1
Name: h_fec_lld, Length: 988, dtype: int64
Column Name:  h_fec_lld_ok
2019-11-07     1540
2019-05-06     1374
2019-05-15     1372
2019-11-24     1302
2019-02-13     1216
               ...
2021-12-02        2
2021-02-28        1
2021-03-27        1
2021-04-03        1
2021-02-04        1
Name: h_fec_lld_ok, Length: 713, dtype: int64
Column Name:  h_fec_lld_okt
2019-11-07    1540
2019-05-06    1374
2019-05-15    1372
2019-11-24    1302
2019-02-13    1216
              ...
2021-12-02       2
2021-02-28       1
2021-03-27       1
2021-04-03       1
2021-02-04       1
Name: h_fec_lld_okt, Length: 713, dtype: int64
Column Name:  h_fec_reg
20190402    2848
20190502    2316
20190625    2194
20190315    1802
20190218    1590
            ...
20200713      10
20190127       8
20190120       2
20190203       2
20200405       2
Name: h_fec_reg, Length: 514, dtype: int64
Column Name:  h_fec_reg_ok
2019-04-02     2848
2019-05-02     2316
2019-06-25     2194
2019-03-15     1802
2019-02-18     1590
               ...
2020-07-13       10
2019-01-27        8
2019-01-20        2
2019-02-03        2
2020-04-05        2
Name: h_fec_reg_ok, Length: 514, dtype: int64
Column Name:  h_fec_reg_okt
2019-04-02    2848
2019-05-02    2316
2019-06-25    2194
2019-03-15    1802
2019-02-18    1590
              ...
2020-07-13      10
2019-01-27       8
2019-01-20       2
2019-02-03       2
2020-04-05       2
Name: h_fec_reg_okt, Length: 514, dtype: int64
Column Name:  h_fec_sda
20190518    1584
20190508    1532
20191208    1373
20190623    1297
20190526    1250
            ...
20200926       1
20201119       1
20201113       1
20210307       1
20190208       1
Name: h_fec_sda, Length: 1368, dtype: int64
Column Name:  h_fec_sda_ok
2019-05-18     1804
2019-05-08     1580
2019-12-08     1500
2019-10-27     1464
2019-11-24     1432
               ...
2020-11-13        1
2021-03-07        1
2021-04-03        1
2021-04-10        1
2021-02-07        1
Name: h_fec_sda_ok, Length: 722, dtype: int64
Column Name:  h_fec_sda_okt
2019-05-18    1804
2019-05-08    1580
2019-12-08    1500
2019-10-27    1464
2019-11-24    1432
              ...
2020-11-13       1
2021-03-07       1
2021-04-03       1
2021-04-10       1
2021-02-07       1
Name: h_fec_sda_okt, Length: 722, dtype: int64
Column Name:  ID_Pais_Origen
157    199916
0         644
232       624
38        228
Name: ID_Pais_Origen, dtype: int64
Column Name:  Cliente_Disp
0     100019
2      79629
3      11933
1       5607
4       2956
5        536
6        423
8        156
7         43
15        24
10        23
12        22
9         20
11         9
14         8
13         4
Name: Cliente_Disp, dtype: int64
Column Name:  aa_Cliente_Disp
0     101393
2      78389
3      11866
1       5593
4       2927
5        534
6        418
8        143
7         43
10        23
15        23
12        20
9         19
11         9
14         8
13         4
Name: aa_Cliente_Disp, dtype: int64
Column Name:  Reservacion
1    101393
0    100019
Name: Reservacion, dtype: int64
Column Name:  aa_Reservacion
0    101393
1    100019
Name: aa_Reservacion, dtype: int64
Column Name:  ID_estatus_reservaciones
9    131069
2     32278
5     18388
1     17107
3      1830
4       586
8       130
7        24
Name: ID_estatus_reservaciones, dtype: int64
Column Name:  h_can_res
00    82061
03    80875
09    19743
06     6163
DI     5848
07     2225
12     1738
08     1092
04      896
10      347
02      160
01      140
05      120
11        4
Name: h_can_res, dtype: int64
Column Name:  h_edo
EGR       61523
EMC       55463
EMX       18123
EGT       17463
EDF        9116
          ...
EKY           2
EGSS          2
EPRI          2
ETFS          2
EPLA          2
Name: h_edo, Length: 147, dtype: int64
Column Name:  h_tfa_total
0.00        105310
5392.00       1474
7236.00       1283
8088.00        900
7662.00        870
             ...
19386.00         1
21768.00         1
42512.94         1
22264.56         1
10103.70         1
Name: h_tfa_total, Length: 11318, dtype: int64
Column Name:  aa_h_tfa_total
0.00        106640
5392.00       1466
7236.00       1224
7662.00        870
7960.00        859
             ...
21452.20         1
21596.40         1
12404.48         1
12489.90         1
171.00           1
Name: aa_h_tfa_total, Length: 11259, dtype: int64
Column Name:  moneda_cve
1    201412
Name: moneda_cve, dtype: int64
Column Name:  h_ult_cam_fec
20200130    1550
20190518    1430
20191020    1400
20200124    1362
20191124    1334
            ...
20200530      10
20200412       4
20200515       4
20190210       4
20190208       2
Name: h_ult_cam_fec, Length: 511, dtype: int64
Column Name:  h_ult_cam_fec_ok
2020-01-30     1550
2019-05-18     1430
2019-10-20     1400
2020-01-24     1362
2019-11-24     1334
               ...
2020-05-30       10
2020-04-12        4
2020-05-15        4
2019-02-10        4
2019-02-08        2
Name: h_ult_cam_fec_ok, Length: 511, dtype: int64
Column Name:  h_ult_cam_fec_okt
2020-01-30    1550
2019-05-18    1430
2019-10-20    1400
2020-01-24    1362
2019-11-24    1334
              ...
2020-05-30      10
2020-04-12       4
2020-05-15       4
2019-02-10       4
2019-02-08       2
Name: h_ult_cam_fec_okt, Length: 511, dtype: int64

In [12]:
# Convertir columnas de fecha a tipo datetime
df['h_fec_reg'] = pd.to_datetime(df['h_fec_reg'].astype(str), format='%Y%m%d')
df['h_fec_lld'] = pd.to_datetime(df['h_fec_lld'].astype(str), format='%Y%m%d')
df['h_fec_sda'] = pd.to_datetime(df['h_fec_sda'].astype(str), format='%Y%m%d')
df['h_ult_cam_fec'] = pd.to_datetime(df['h_ult_cam_fec'].astype(str), format='%Y%m%d')
df['h_res_fec'] = pd.to_datetime(df['h_res_fec'].astype(str), format='%Y%m%d')

In [13]:
# Verificar el resto de valores categoricos
for column_name in df.columns:
    value_counts = df[column_name].value_counts()
    print("Column Name: ", column_name)
    print(value_counts)

Column Name:  ID_Reserva
0         1
135255    1
135257    1
135258    1
135259    1
         ..
67565     1
67566     1
67567     1
67568     1
203001    1
Name: ID_Reserva, Length: 201412, dtype: int64
Column Name:  Fecha_hoy
2020-02-18    1496
2020-04-02    1484
2019-04-02    1465
2020-02-20    1372
2020-03-04    1162
              ...
2021-01-19       6
2019-01-06       6
2019-01-27       4
2019-01-20       1
2019-02-03       1
Name: Fecha_hoy, Length: 824, dtype: int64
Column Name:  h_res_fec
2019-04-02    2930
2019-05-02    2316
2019-06-25    2204
2019-03-15    1788
2019-07-31    1608
              ...
2020-04-18      10
2019-01-27       8
2019-01-20       2
2019-02-03       2
2020-04-05       2
Name: h_res_fec, Length: 481, dtype: int64
Column Name:  h_res_fec_ok
2019-04-02     2930
2019-05-02     2316
2019-06-25     2204
2019-03-15     1788
2019-07-31     1608
               ...
2020-04-18       10
2019-01-27        8
2019-01-20        2
2019-02-03        2
2020-04-05        2
Name: h_res_fec_ok, Length: 481, dtype: int64
Column Name:  h_res_fec_okt
2019-04-02    2930
2019-05-02    2316
2019-06-25    2204
2019-03-15    1788
2019-07-31    1608
              ...
2020-04-18      10
2019-01-27       8
2019-01-20       2
2019-02-03       2
2020-04-05       2
Name: h_res_fec_okt, Length: 481, dtype: int64
Column Name:  h_num_per
0     100019
2      71325
3      14922
4       7710
1       4900
5       1280
6        781
8        228
7         96
12        40
10        21
11        18
9         17
17        13
32        10
16         8
18         6
14         6
19         5
13         3
20         2
15         2
Name: h_num_per, dtype: int64
Column Name:  aa_h_num_per
0     101393
2      70108
3      14861
4       7654
1       4887
5       1276
6        775
8        215
7         96
12        38
10        20
11        18
9         17
17        13
32        10
16         8
18         6
14         6
19         5
13         3
20         2
15         1
Name: aa_h_num_per, dtype: int64
Column Name:  h_num_adu
0     100019
2      79629
3      11933
1       5607
4       2956
5        536
6        423
8        156
7         43
15        24
10        23
12        22
9         20
11         9
14         8
13         4
Name: h_num_adu, dtype: int64
Column Name:  aa_h_num_adu
0     101393
2      78389
3      11866
1       5593
4       2927
5        534
6        418
8        143
7         43
10        23
15        23
12        20
9         19
11         9
14         8
13         4
Name: aa_h_num_adu, dtype: int64
Column Name:  h_num_men
0     196972
1       2645
2       1555
3        168
4         31
5         17
15        10
7          7
6          6
8          1
Name: h_num_men, dtype: int64
Column Name:  aa_h_num_men
0     197024
1       2613
2       1538
3        165
4         31
5         17
15        10
7          7
6          6
8          1
Name: aa_h_num_men, dtype: int64
Column Name:  h_num_noc
0      100222
3       38432
2       28486
4       16274
7        8672
1        4675
5        2477
6        1008
14        643
8         140
10         94
9          66
11         65
15         36
12         29
13         17
21         15
28         10
16          7
35          6
20          5
17          4
19          3
182         3
36          2
18          2
89          2
63          2
87          2
22          1
48          1
81          1
84          1
687         1
52          1
24          1
27          1
191         1
321         1
74          1
59          1
34          1
Name: h_num_noc, dtype: int64
Column Name:  aa_h_num_noc
0      101596
3       37757
2       28128
4       16048
7        8612
1        4669
5        2463
6        1007
14        643
8         138
10         94
9          66
11         64
12         29
13         17
21         15
28         10
16          7
15          7
35          6
20          5
17          4
182         3
19          3
36          2
63          2
87          2
18          2
321         1
74          1
27          1
24          1
52          1
191         1
84          1
34          1
48          1
22          1
81          1
687         1
59          1
Name: aa_h_num_noc, dtype: int64
Column Name:  h_tot_hab
1    100907
0    100019
2       308
3       166
4         8
5         3
6         1
Name: h_tot_hab, dtype: int64
Column Name:  aa_h_tot_hab
0    101393
1     99551
2       296
3       160
4         8
5         3
6         1
Name: aa_h_tot_hab, dtype: int64
Column Name:  ID_Programa
1    201412
Name: ID_Programa, dtype: int64
Column Name:  ID_Paquete
1    116562
2     84716
5        92
3        40
4         2
Name: ID_Paquete, dtype: int64
Column Name:  ID_Segmento_Comp
17    73066
14    27298
5     26630
16    16776
12    15425
18     9082
1      6013
13     5770
8      4579
10     3212
19     3185
11     2811
9      2716
7      2020
6      1532
4       677
0       578
2        34
15        4
3         4
Name: ID_Segmento_Comp, dtype: int64
Column Name:  ID_Agencia
99     31521
112    25697
86     12973
14     12189
116     8846
       ...
37        10
57         8
118        6
115        4
64         2
Name: ID_Agencia, Length: 120, dtype: int64
Column Name:  ID_empresa
1    201412
Name: ID_empresa, dtype: int64
Column Name:  ID_Tipo_Habitacion
4     51996
19    50840
17    30806
6     13824
25    11100
13    10445
5      6029
23     5785
26     4907
24     3843
7      2124
27     1976
21     1787
12     1356
18     1328
22     1156
20      354
14      338
1       229
2       203
3       190
11      170
15      150
10      146
9       136
8       118
16       66
0        10
Name: ID_Tipo_Habitacion, dtype: int64
Column Name:  ID_canal
1     82061
4     80875
10    19743
7      6163
0      5848
8      2225
13     1738
9      1092
5       896
11      347
3       160
2       140
6       120
12        4
Name: ID_canal, dtype: int64
Column Name:  h_fec_lld
2019-11-07    1540
2019-05-06    1374
2019-05-15    1372
2019-11-24    1302
2019-02-13    1216
              ...
2021-12-02       2
2021-02-28       1
2021-03-27       1
2021-04-03       1
2021-02-04       1
Name: h_fec_lld, Length: 713, dtype: int64
Column Name:  h_fec_lld_ok
2019-11-07     1540
2019-05-06     1374
2019-05-15     1372
2019-11-24     1302
2019-02-13     1216
               ...
2021-12-02        2
2021-02-28        1
2021-03-27        1
2021-04-03        1
2021-02-04        1
Name: h_fec_lld_ok, Length: 713, dtype: int64
Column Name:  h_fec_lld_okt
2019-11-07    1540
2019-05-06    1374
2019-05-15    1372
2019-11-24    1302
2019-02-13    1216
              ...
2021-12-02       2
2021-02-28       1
2021-03-27       1
2021-04-03       1
2021-02-04       1
Name: h_fec_lld_okt, Length: 713, dtype: int64
Column Name:  h_fec_reg
2019-04-02    2848
2019-05-02    2316
2019-06-25    2194
2019-03-15    1802
2019-02-18    1590
              ...
2020-07-13      10
2019-01-27       8
2019-01-20       2
2019-02-03       2
2020-04-05       2
Name: h_fec_reg, Length: 514, dtype: int64
Column Name:  h_fec_reg_ok
2019-04-02     2848
2019-05-02     2316
2019-06-25     2194
2019-03-15     1802
2019-02-18     1590
               ...
2020-07-13       10
2019-01-27        8
2019-01-20        2
2019-02-03        2
2020-04-05        2
Name: h_fec_reg_ok, Length: 514, dtype: int64
Column Name:  h_fec_reg_okt
2019-04-02    2848
2019-05-02    2316
2019-06-25    2194
2019-03-15    1802
2019-02-18    1590
              ...
2020-07-13      10
2019-01-27       8
2019-01-20       2
2019-02-03       2
2020-04-05       2
Name: h_fec_reg_okt, Length: 514, dtype: int64
Column Name:  h_fec_sda
2019-05-18    1804
2019-05-08    1580
2019-12-08    1500
2019-10-27    1464
2019-11-24    1432
              ...
2020-11-13       1
2021-03-07       1
2021-04-03       1
2021-04-10       1
2021-02-07       1
Name: h_fec_sda, Length: 722, dtype: int64
Column Name:  h_fec_sda_ok
2019-05-18     1804
2019-05-08     1580
2019-12-08     1500
2019-10-27     1464
2019-11-24     1432
               ...
2020-11-13        1
2021-03-07        1
2021-04-03        1
2021-04-10        1
2021-02-07        1
Name: h_fec_sda_ok, Length: 722, dtype: int64
Column Name:  h_fec_sda_okt
2019-05-18    1804
2019-05-08    1580
2019-12-08    1500
2019-10-27    1464
2019-11-24    1432
              ...
2020-11-13       1
2021-03-07       1
2021-04-03       1
2021-04-10       1
2021-02-07       1
Name: h_fec_sda_okt, Length: 722, dtype: int64
Column Name:  ID_Pais_Origen
157    199916
0         644
232       624
38        228
Name: ID_Pais_Origen, dtype: int64
Column Name:  Cliente_Disp
0     100019
2      79629
3      11933
1       5607
4       2956
5        536
6        423
8        156
7         43
15        24
10        23
12        22
9         20
11         9
14         8
13         4
Name: Cliente_Disp, dtype: int64
Column Name:  aa_Cliente_Disp
0     101393
2      78389
3      11866
1       5593
4       2927
5        534
6        418
8        143
7         43
10        23
15        23
12        20
9         19
11         9
14         8
13         4
Name: aa_Cliente_Disp, dtype: int64
Column Name:  Reservacion
1    101393
0    100019
Name: Reservacion, dtype: int64
Column Name:  aa_Reservacion
0    101393
1    100019
Name: aa_Reservacion, dtype: int64
Column Name:  ID_estatus_reservaciones
9    131069
2     32278
5     18388
1     17107
3      1830
4       586
8       130
7        24
Name: ID_estatus_reservaciones, dtype: int64
Column Name:  h_can_res
00    82061
03    80875
09    19743
06     6163
DI     5848
07     2225
12     1738
08     1092
04      896
10      347
02      160
01      140
05      120
11        4
Name: h_can_res, dtype: int64
Column Name:  h_edo
EGR       61523
EMC       55463
EMX       18123
EGT       17463
EDF        9116
          ...
EKY           2
EGSS          2
EPRI          2
ETFS          2
EPLA          2
Name: h_edo, Length: 147, dtype: int64
Column Name:  h_tfa_total
0.00        105310
5392.00       1474
7236.00       1283
8088.00        900
7662.00        870
             ...
19386.00         1
21768.00         1
42512.94         1
22264.56         1
10103.70         1
Name: h_tfa_total, Length: 11318, dtype: int64
Column Name:  aa_h_tfa_total
0.00        106640
5392.00       1466
7236.00       1224
7662.00        870
7960.00        859
             ...
21452.20         1
21596.40         1
12404.48         1
12489.90         1
171.00           1
Name: aa_h_tfa_total, Length: 11259, dtype: int64
Column Name:  moneda_cve
1    201412
Name: moneda_cve, dtype: int64
Column Name:  h_ult_cam_fec
2020-01-30    1550
2019-05-18    1430
2019-10-20    1400
2020-01-24    1362
2019-11-24    1334
              ...
2020-05-30      10
2020-04-12       4
2020-05-15       4
2019-02-10       4
2019-02-08       2
Name: h_ult_cam_fec, Length: 511, dtype: int64
Column Name:  h_ult_cam_fec_ok
2020-01-30     1550
2019-05-18     1430
2019-10-20     1400
2020-01-24     1362
2019-11-24     1334
               ...
2020-05-30       10
2020-04-12        4
2020-05-15        4
2019-02-10        4
2019-02-08        2
Name: h_ult_cam_fec_ok, Length: 511, dtype: int64
Column Name:  h_ult_cam_fec_okt
2020-01-30    1550
2019-05-18    1430
2019-10-20    1400
2020-01-24    1362
2019-11-24    1334
              ...
2020-05-30      10
2020-04-12       4
2020-05-15       4
2019-02-10       4
2019-02-08       2
Name: h_ult_cam_fec_okt, Length: 511, dtype: int64

In [14]:
df.head(20)

,ID_Reserva,Fecha_hoy,h_res_fec,h_res_fec_ok,h_res_fec_okt,h_num_per,aa_h_num_per,h_num_adu,aa_h_num_adu,h_num_men,...,aa_Reservacion,ID_estatus_reservaciones,h_can_res,h_edo,h_tfa_total,aa_h_tfa_total,moneda_cve,h_ult_cam_fec,h_ult_cam_fec_ok,h_ult_cam_fec_okt
0,0,2019-08-16,2019-08-16,2019-08-16,2019-08-16,2,0,2,0,0,...,0,9,09,EMX,2659.98,0.0,1,2019-11-10,2019-11-10,2019-11-10
1,1,2019-10-22,2019-10-22,2019-10-22,2019-10-22,4,0,4,0,0,...,0,9,09,EGT,1764.00,0.0,1,2019-12-05,2019-12-05,2019-12-05
2,2,2019-10-28,2019-10-28,2019-10-28,2019-10-28,2,0,2,0,0,...,0,9,09,EMC,2660.04,0.0,1,2019-12-05,2019-12-05,2019-12-05
3,3,2019-10-28,2019-10-28,2019-10-28,2019-10-28,4,0,3,0,0,...,0,9,09,EGT,1995.03,0.0,1,2019-12-11,2019-12-11,2019-12-11
4,4,2019-10-28,2019-10-28,2019-10-28,2019-10-28,2,0,2,0,0,...,0,9,12,EMX,13369.92,0.0,1,2019-12-12,2019-12-12,2019-12-12
5,5,2019-08-05,2019-08-05,2019-08-05,2019-08-05,6,0,6,0,0,...,0,9,11,EGT,2660.04,0.0,1,2019-12-05,2019-12-05,2019-12-05
6,6,2019-07-19,2019-07-19,2019-07-19,2019-07-19,2,0,2,0,0,...,0,2,09,EGR,3331.98,0.0,1,2019-07-24,2019-07-24,2019-07-24
7,7,2019-07-19,2019-07-19,2019-07-19,2019-07-19,2,0,2,0,0,...,0,9,00,EMC,8809.92,0.0,1,2019-08-25,2019-08-25,2019-08-25
8,8,2019-07-19,2019-07-19,2019-07-19,2019-07-19,3,0,2,0,0,...,0,9,09,EGR,2548.00,0.0,1,2019-08-29,2019-08-29,2019-08-29
9,9,2019-05-06,2019-05-06,2019-05-06,2019-05-06,2,0,2,0,0,...,0,9,09,EMC,2548.00,0.0,1,2019-08-29,2019-08-29,2019-08-29
10,10,2019-12-17,2019-12-17,2019-12-17,2019-12-17,2,0,2,0,0,...,0,9,09,EMX,7000.00,0.0,1,2019-12-28,2019-12-28,2019-12-28
11,11,2019-11-01,2019-11-01,2019-11-01,2019-11-01,1,0,1,0,0,...,0,9,00,EMC,2673.99,0.0,1,2019-11-10,2019-11-10,2019-11-10
12,12,2019-07-17,2019-07-17,2019-07-17,2019-07-17,2,0,2,0,0,...,0,9,00,EMC,2044.00,0.0,1,2019-10-23,2019-10-23,2019-10-23
13,13,2019-10-11,2019-10-11,2019-10-11,2019-10-11,2,0,2,0,0,...,0,9,06,EMC,14170.32,0.0,1,2019-10-24,2019-10-24,2019-10-24
14,14,2019-10-11,2019-10-11,2019-10-11,2019-10-11,2,0,2,0,0,...,0,9,06,EMC,15455.92,0.0,1,2019-10-24,2019-10-24,2019-10-24
15,15,2019-04-27,2019-04-27,2019-04-27,2019-04-27,3,0,1,0,2,...,0,2,12,EGR,6377.16,0.0,1,2019-10-11,2019-10-11,2019-10-11
16,16,2019-08-17,2019-08-17,2019-08-17,2019-08-17,2,0,2,0,0,...,0,2,03,EGR,8088.00,0.0,1,2019-11-06,2019-11-06,2019-11-06
17,17,2019-08-17,2019-08-17,2019-08-17,2019-08-17,2,0,2,0,0,...,0,2,03,EGR,8088.00,0.0,1,2019-11-06,2019-11-06,2019-11-06
18,18,2019-08-17,2019-08-17,2019-08-17,2019-08-17,2,0,2,0,0,...,0,2,03,EGR,8088.00,0.0,1,2019-11-06,2019-11-06,2019-11-06
19,19,2019-08-17,2019-08-17,2019-08-17,2019-08-17,2,0,2,0,0,...,0,2,03,EGR,8088.00,0.0,1,2019-11-06,2019-11-06,2019-11-06