In [1]:
import pandas as pd
import numpy as np
import warnings

In [2]:
warnings.simplefilter("ignore")

In [3]:
df = pd.read_csv("C:/a space/S8/Reto/iar_Reservaciones.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203002 entries, 0 to 203001
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID_Reserva                203002 non-null  int64
 1   Fecha_hoy                 203002 non-null  object
 2   h_res_fec                 203002 non-null  int64
 3   h_res_fec_ok              203002 non-null  object
 4   h_res_fec_okt             203002 non-null  object
 5   h_num_per                 203002 non-null  int64
 6   aa_h_num_per              203002 non-null  int64
 7   h_num_adu                 203002 non-null  int64
 8   aa_h_num_adu              203002 non-null  int64
 9   h_num_men                 203002 non-null  int64
 10  aa_h_num_men              203002 non-null  int64
 11  h_num_noc                 203002 non-null  int64
 12  aa_h_num_noc              203002 non-null  int64
 13  h_tot_hab                 203002 non-null  int64
 14  aa_h_tot_hab              203002 non-null  int64
 15  ID_Programa               203002 non-null  int64
 16  ID_Paquete                203002 non-null  int64
 17  ID_Segmento_Comp          203002 non-null  int64
 18  ID_Agencia                203002 non-null  int64
 19  ID_empresa                203002 non-null  int64
 20  ID_Tipo_Habitacion        203002 non-null  int64
 21  ID_canal                  203002 non-null  int64
 22  h_fec_lld                 203002 non-null  object
 23  h_fec_lld_ok              203002 non-null  object
 24  h_fec_lld_okt             203002 non-null  object
 25  h_fec_reg                 203002 non-null  object
 26  h_fec_reg_ok              203002 non-null  object
 27  h_fec_reg_okt             203002 non-null  object
 28  h_fec_sda                 203002 non-null  object
 29  h_fec_sda_ok              203002 non-null  object
 30  h_fec_sda_okt             203002 non-null  object
 31  ID_Pais_Origen            203002 non-null  int64
 32  Cliente_Disp              203002 non-null  int64
 33  aa_Cliente_Disp           203002 non-null  int64
 34  Reservacion               203002 non-null  int64
 35  aa_Reservacion            203002 non-null  int64
 36  ID_estatus_reservaciones  203002 non-null  int64
 37  h_can_res                 203002 non-null  object
 38  h_cod_reserva             203002 non-null  object
 39  h_edo                     203002 non-null  object
 40  h_codigop                 203002 non-null  object
 41  h_correo_e                0 non-null       float64
 42  h_nom                     0 non-null       float64
 43  h_tfa_total               203002 non-null  float64
 44  aa_h_tfa_total            203002 non-null  float64
 45  moneda_cve                203002 non-null  int64
 46  h_ult_cam_fec             203002 non-null  object
 47  h_ult_cam_fec_ok          203002 non-null  object
 48  h_ult_cam_fec_okt         203002 non-null  object
dtypes: float64(4), int64(26), object(19)
memory usage: 75.9+ MB

In [6]:
df.drop(['h_correo_e', 'h_nom'], axis='columns', inplace=True)

In [7]:
df.head()

,ID_Reserva,Fecha_hoy,h_res_fec,h_res_fec_ok,h_res_fec_okt,h_num_per,aa_h_num_per,h_num_adu,aa_h_num_adu,h_num_men,...,h_can_res,h_cod_reserva,h_edo,h_codigop,h_tfa_total,aa_h_tfa_total,moneda_cve,h_ult_cam_fec,h_ult_cam_fec_ok,h_ult_cam_fec_okt
0,0,2019-08-16,20190816,2019-08-16,2019-08-16,2,0,2,0,0,...,09,,EMX,01500,2659.98,0.0,1,20191110,2019-11-10,2019-11-10
1,1,2019-10-22,20191022,2019-10-22,2019-10-22,4,0,4,0,0,...,09,,EGT,023541,1764.00,0.0,1,20191205,2019-12-05,2019-12-05
2,2,2019-10-28,20191028,2019-10-28,2019-10-28,2,0,2,0,0,...,09,,EMC,59800,2660.04,0.0,1,20191205,2019-12-05,2019-12-05
3,3,2019-10-28,20191028,2019-10-28,2019-10-28,4,0,3,0,0,...,09,,EGT,37219,1995.03,0.0,1,20191211,2019-12-11,2019-12-11
4,4,2019-10-28,20191028,2019-10-28,2019-10-28,2,0,2,0,0,...,12,74101652-3_2394,EMX,15300,13369.92,0.0,1,20191212,2019-12-12,2019-12-12